name: Build PDF

on:
  push:
    branches:
      - develop
      - master
      - main
      - release/*
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: false

jobs:
  build-pdf:
    uses: kolosovpetro/github-latex-template/.github/workflows/build-pdf-template.yml@main
    with:
      file_name: 'RSAEncryptionExplained'
      runs_on: 'ubuntu-latest'
      workflow_name: 'Build PDF'
      build_assets_path: |
        src/RSAEncryptionExplained.tex
        src/RSAEncryptionExplained.bbl
        src/RSAEncryptionExplained.bib
        src/sections
        src/img
      working_directory_for_latex: 'src'
